;;; ri-extend-test.el --- Tests for ri-extend.el -*- lexical-binding: t; -*-
(require 'tab-line)

(require 'cl-lib)
(require 'ert)
(require 'ri)

(defmacro ri-extend-test--with-buffer (text &rest body)
  "Run BODY in a temporary buffer containing TEXT."
  (declare (indent 1))
  `(with-temp-buffer
     (insert ,text)
     (goto-char (point-min))
     ,@body))

(defmacro ri-extend-test--with-json-buffer (text &rest body)
  "Run BODY in a temporary JSON buffer backed by tree-sitter."
  (declare (indent 1))
  `(ri-extend-test--with-buffer ,text
     (unless (and (treesit-available-p)
                  (treesit-language-available-p 'json))
       (ert-skip "JSON tree-sitter grammar unavailable"))
     (treesit-parser-create 'json)
     ,@body))

(defun ri-extend-test--highlighted-p (pos)
  "Return non-nil when POS has the semantic highlight face."
  (cl-some
   (lambda (overlay)
     (eq (overlay-get overlay 'face) 'sr-highlight-face))
   (overlays-at pos)))

(ert-deftest ri-extend-test-toggle-command-enters-extend-interactively ()
  (ri-extend-test--with-buffer "alpha beta\n"
    (setq sr-submode 'word)
    (should (commandp #'ri-toggle-extend))
    (call-interactively #'ri-toggle-extend)
    (should (ri--selection-active-p))
    (should (equal (ri--selection-bounds) (cons 1 6)))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (= (point) 5))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-submode-switch-preserves-selection ()
  (ri-extend-test--with-buffer "foo bar baz\n"
    (dolist
        (case
         '((ri-extend-set-line-star-mode line-star)
           (ri-extend-set-line-mode line)
           (ri-extend-set-paragraph-mode paragraph)
           (ri-extend-set-character-mode char)
           (ri-extend-set-word-mode word)
           (ri-extend-set-word-star-mode word-star)
           (ri-extend-set-word-plus-mode word-plus)
           (ri-extend-set-subword-mode subword)))
      (pcase-let ((`(,setter ,submode) case))
        (dolist (swap '(nil t))
          (goto-char 2)
          (setq sr-submode 'char)
          (should (ri--enter-extend))
          (let ((before (ri--selection-bounds)))
            (should (equal before (cons 2 3)))
            (when swap
              (ri-swap-cursor)
              (should (equal (ri--selection-bounds) before)))
            (funcall setter)
            (should (eq sr-submode submode))
            (should (ri--selection-active-p))
            (should (eq (ri--selection-state-active-edge ri--selection)
                        (if swap 'start 'end)))
            (should (equal (ri--selection-bounds) before)))
          (ri--exit-extend))))))

(ert-deftest ri-extend-test-line-to-word-after-swap-preserves-extend ()
  (ri-extend-test--with-buffer
      "zero alpha\nbeta gamma\ndelta epsilon\n"
    (goto-char 8)
    (setq sr-submode 'char)
    (should (ri--enter-extend))
    (ri-extend-nav-down)
    (ri-extend-nav-down)
    (let ((extended-bounds (ri--selection-bounds)))
      ;; Two vertical downs from column 7 restore column 7 on line 3.
      (should (equal extended-bounds (cons 8 31)))
      (should
       (equal (buffer-substring-no-properties
               (car extended-bounds) (cdr extended-bounds))
              "pha\nbeta gamma\ndelta ep"))
      (ri-extend-set-line-mode)
      (should (equal (ri--selection-bounds) extended-bounds))
      (ri-swap-cursor)
      (should (equal (ri--selection-bounds) extended-bounds))
      (ri-extend-set-word-mode)
      (should (eq sr-submode 'word))
      (should (equal (ri--selection-bounds) extended-bounds))
      (ri-extend-nav-right)
      (should (equal (ri--selection-bounds) (cons 12 31)))
      (ri-smart-undo)
      (should (equal (ri--selection-bounds) extended-bounds)))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-fine-undo-redo-splits-grouped-insertion ()
  (with-temp-buffer
    (buffer-enable-undo)
    (insert "abc")
    (undo-boundary)
    (let ((last-command nil))
      (cl-labels
          ((dispatch (command)
             (let ((this-command command))
               (call-interactively command)
               (setq last-command this-command))))
        (dolist (expected '("ab" "a" ""))
          (dispatch #'ri-fine-undo)
          (should (equal (buffer-string) expected)))
        (dolist (expected '("a" "ab" "abc"))
          (dispatch #'ri-fine-redo)
          (should (equal (buffer-string) expected)))))))

(ert-deftest ri-extend-test-z-undo-only-history-exhaustion ()
  (with-temp-buffer
    (buffer-enable-undo)
    (insert "base")
    (setq buffer-undo-list nil)
    (insert " change")
    (undo-boundary)
    (let ((last-command nil))
      (cl-labels
          ((dispatch ()
             (let ((this-command #'ri-undo-only))
               (call-interactively #'ri-undo-only)
               (setq last-command this-command))))
        (dispatch)
        (should (equal (buffer-string) "base"))
        (dotimes (_ 2)
          (setq last-command #'ri--press-layer)
          (should-error (dispatch) :type 'user-error)
          (should (equal (buffer-string) "base")))
        (insert " fresh")
        (undo-boundary)
        (setq last-command #'self-insert-command)
        (dispatch)
        (should (equal (buffer-string) "base"))))))


(ert-deftest ri-extend-test-node-extends-across-named-siblings ()
  (ri-extend-test--with-json-buffer
      "[{\"x\": 123}, true, {\"y\": {}}]"
    (setq sr-submode 'char)
    (goto-char 2)
    (ri-extend-set-node-mode)
    (should (eq sr-submode 'node))
    (should (equal (sr--get-current-unit-bounds) (cons 2 12)))
    (should (ri--enter-extend))
    ;; Ki recipe: NODE, Extend, Right, Right, Left.
    (ri-extend-nav-right)
    (ri-extend-nav-right)
    (ri-extend-nav-left)
    (let ((bounds (ri--selection-bounds)))
      (should (equal (buffer-substring-no-properties
                      (car bounds) (cdr bounds))
                     "{\"x\": 123}, true"))
      (should (= (point) (1- (cdr bounds)))))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-momentary-char-navigation-records-origin-and-restores ()
  (ri-extend-test--with-buffer "ab\ncd"
    (setq sr-submode 'line)
    (ri-momentary-char-right)
    (should (= (point) 2))
    (should (eq sr-submode 'char))
    (should (eq ri--momentary-origin-submode 'line))
    (should (equal (sr--get-current-unit-bounds) (cons 2 3)))
    (should (ri-extend-test--highlighted-p 2))
    (should-not (ri-extend-test--highlighted-p 1))
    (ri-momentary-char-left)
    (should (= (point) 1))
    (ri-momentary-char-down)
    (should (= (point) 4))
    (ri-momentary-char-up)
    (should (= (point) 1))
    (should (eq ri--momentary-origin-submode 'line))

    (let ((restore-point (point)))
      (ri--restore-momentary-submode)
      (should (eq sr-submode 'line))
      (should (= (point) restore-point))
      (should-not ri--momentary-origin-submode))

    (ri-extend-set-line-mode)
    (should (ri--enter-extend))
    (should (equal (ri--selection-bounds) (cons 1 3)))
    (ri-momentary-char-right)
    (should (equal (ri--selection-bounds) (cons 1 4)))
    (should (= (point) 3))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'char))
    (should (eq ri--momentary-origin-submode 'line))
    (ri--restore-momentary-submode)
    (should (equal (ri--selection-bounds) (cons 1 4)))
    (should (= (point) 3))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'line))
    (ri--exit-extend)

    (goto-char 4)
    (ri-extend-set-line-mode)
    (should (ri--enter-extend))
    (ri-swap-cursor)
    (should (equal (ri--selection-bounds) (cons 4 6)))
    (ri-momentary-char-left)
    (should (equal (ri--selection-bounds) (cons 3 6)))
    (should (= (point) 3))
    (should (eq (ri--selection-state-active-edge ri--selection) 'start))
    (should (eq sr-submode 'char))
    (should (eq ri--momentary-origin-submode 'line))
    (ri--restore-momentary-submode)
    (should (equal (ri--selection-bounds) (cons 3 6)))
    (should (= (point) 3))
    (should (eq (ri--selection-state-active-edge ri--selection) 'start))
    (should (eq sr-submode 'line))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-momentary-char-vertical-remembers-goal-column ()
  (ri-extend-test--with-buffer "abcd\nef\nghij"
    ;; "abcd\nef\nghij": line 1 = 1-4, line 2 = 6-7, line 3 = 9-12.
    (goto-char 3)
    (ri-momentary-char-down)
    (should (= (point) 7))             ; goal 2 clamps to line 2's last char
    (ri-momentary-char-down)
    (should (= (point) 11))            ; goal 2 restored on line 3
    (ri-momentary-char-up)
    (should (= (point) 7))             ; goal 2 clamps again
    (ri-momentary-char-up)
    (should (= (point) 3))             ; goal 2 restored on line 1
    ;; Horizontal movement resets the goal column.
    (ri-momentary-char-right)
    (should (= (point) 4))
    (ri-momentary-char-down)
    (should (= (point) 7))             ; new goal 3 clamps on line 2
    ;; Extend mode keeps point on the active end edge at the goal column.
    (goto-char 2)
    (setq sr--goal-column nil)
    (should (ri--enter-extend))
    (ri-momentary-char-down)
    (should (= (point) 7))             ; goal 1 clamps to line 2's last char
    (should (equal (ri--selection-bounds) (cons 2 8)))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (ri-momentary-char-down)
    (should (= (point) 10))            ; goal 1 restored on line 3
    (should (equal (ri--selection-bounds) (cons 2 11)))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-momentary-line-navigation-records-origin-and-restores ()
  (ri-extend-test--with-buffer "ab\ncd"
    (setq sr-submode 'char)
    (ri-momentary-line-down)
    (should (= (point) 4))
    (should (eq sr-submode 'line))
    (should (eq ri--momentary-origin-submode 'char))
    (should (equal (sr--get-current-unit-bounds) (cons 4 6)))
    (should (ri-extend-test--highlighted-p 4))
    (should-not (ri-extend-test--highlighted-p 1))
    (ri-momentary-line-up)
    (should (= (point) 1))
    (should (eq ri--momentary-origin-submode 'char))

    (let ((restore-point (point)))
      (ri--restore-momentary-submode)
      (should (eq sr-submode 'char))
      (should (= (point) restore-point))
      (should-not ri--momentary-origin-submode))

    (ri-extend-set-line-mode)
    (should (ri--enter-extend))
    (should (equal (ri--selection-bounds) (cons 1 3)))
    (ri-momentary-line-down)
    (should (equal (ri--selection-bounds) (cons 1 6)))
    (should (= (point) 5))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'line))
    (should (eq ri--momentary-origin-submode 'line))
    (ri--restore-momentary-submode)
    (should (equal (ri--selection-bounds) (cons 1 6)))
    (should (= (point) 5))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'line))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-momentary-word-plus-navigation-records-origin-and-restores ()
  (ri-extend-test--with-buffer "alpha,beta\n  gamma"
    (setq sr-submode 'char)
    (ri-momentary-word-plus-right)
    (should (= (point) 6))
    (should (eq sr-submode 'word-plus))
    (should (eq ri--momentary-origin-submode 'char))
    (should (equal (sr--get-current-unit-bounds) (cons 6 7)))
    (should (ri-extend-test--highlighted-p 6))
    (should-not (ri-extend-test--highlighted-p 5))
    (ri-momentary-word-plus-right)
    (should (= (point) 7))
    (ri-momentary-word-plus-left)
    (should (= (point) 6))
    (goto-char (point-min))
    (ri-momentary-word-plus-down)
    (should (= (point) 14))
    (ri-momentary-word-plus-up)
    (should (= (point) 1))
    (should (eq ri--momentary-origin-submode 'char))

    (let ((restore-point (point)))
      (ri--restore-momentary-submode)
      (should (eq sr-submode 'char))
      (should (= (point) restore-point))
      (should-not ri--momentary-origin-submode))

    (ri-extend-set-word-mode)
    (should (ri--enter-extend))
    (should (equal (ri--selection-bounds) (cons 1 6)))
    (ri-momentary-word-plus-right)
    (should (equal (ri--selection-bounds) (cons 1 7)))
    (should (= (point) 6))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'word-plus))
    (should (eq ri--momentary-origin-submode 'word))
    (ri--restore-momentary-submode)
    (should (equal (ri--selection-bounds) (cons 1 7)))
    (should (= (point) 6))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (should (eq sr-submode 'word))
    (ri--exit-extend)

    (goto-char 7)
    (ri-extend-set-word-mode)
    (should (ri--enter-extend))
    (ri-swap-cursor)
    (should (equal (ri--selection-bounds) (cons 7 11)))
    (ri-momentary-word-plus-left)
    (should (equal (ri--selection-bounds) (cons 6 11)))
    (should (= (point) 6))
    (should (eq (ri--selection-state-active-edge ri--selection) 'start))
    (should (eq sr-submode 'word-plus))
    (should (eq ri--momentary-origin-submode 'word))
    (ri--restore-momentary-submode)
    (should (equal (ri--selection-bounds) (cons 6 11)))
    (should (= (point) 6))
    (should (eq (ri--selection-state-active-edge ri--selection) 'start))
    (should (eq sr-submode 'word))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-momentary-release-in-node-retargets-lowest ()
  (ri-extend-test--with-buffer "(defun foo ()\n  (bar baz))"
    (unless (and (treesit-available-p)
                 (treesit-language-available-p 'elisp))
      (ert-skip "Elisp tree-sitter grammar unavailable"))
    (treesit-parser-create 'elisp)
    ;; CHAR: move right onto the space after `bar`; release must select the
    ;; lowest node at that position like a mouse click, not the adjacent
    ;; token from the keyboard top-node rule.
    (setq sr-submode 'node)
    (goto-char 20)                     ; `r' of bar
    (sr--update-highlight)
    (ri-momentary-char-right)
    (should (= (point) 21))
    (should (eq sr-submode 'char))
    (should (eq ri--momentary-origin-submode 'node))
    (ri--restore-momentary-submode)
    (should (eq sr-submode 'node))
    (should (= (point) 21))
    (should (equal (sr--get-current-unit-bounds) (cons 17 26)))
    (should (equal (buffer-substring-no-properties 17 26) "(bar baz)"))
    (should-not ri--momentary-origin-submode)
    ;; WORD+: down lands on the opening paren; release selects the `(' leaf
    ;; node exactly as a click there would.
    (setq sr-submode 'node)
    (goto-char (point-min))
    (sr--update-highlight)
    (ri-momentary-word-plus-down)
    (should (= (point) 17))
    (should (eq ri--momentary-origin-submode 'node))
    (ri--restore-momentary-submode)
    (should (eq sr-submode 'node))
    (should (= (point) 17))
    (should (equal (sr--get-current-unit-bounds) (cons 17 18)))
    (should (equal (buffer-substring-no-properties 17 18) "("))))

(ert-deftest ri-extend-test-normal-submode-switch-snaps-to-unit-start ()
  (ri-extend-test--with-buffer "  alpha beta\n"
    (dolist
        (case
         '((ri-extend-set-line-star-mode line-star 1 (1 . 13))
           (ri-extend-set-line-mode line 3 (3 . 13))
           (ri-extend-set-paragraph-mode paragraph 1 (1 . 14))
           (ri-extend-set-character-mode char 1 (1 . 2))
           (ri-extend-set-word-mode word 3 (3 . 8))
           (ri-extend-set-word-star-mode word-star 3 (3 . 8))
           (ri-extend-set-word-plus-mode word-plus 3 (3 . 8))
           (ri-extend-set-subword-mode subword 3 (3 . 8))))
      (pcase-let
          ((`(,setter ,submode ,expected-point ,expected-bounds) case))
        (goto-char (point-min))
        (setq sr-submode 'char)
        (funcall setter)
        (should (eq sr-submode submode))
        (should (= (point) expected-point))
        (should (equal (sr--get-current-unit-bounds)
                       expected-bounds))))))

(ert-deftest ri-extend-test-paragraph-switch-keeps-empty-line-current ()
  (ri-extend-test--with-buffer "\nfoo\n"
    (setq sr-submode 'char)
    (ri-extend-set-paragraph-mode)
    (should (eq sr-submode 'paragraph))
    (should (= (point) (point-min)))
    (should (equal (sr--get-current-unit-bounds)
                   (cons (point-min) (point-min))))))

(ert-deftest ri-extend-test-paragraph-navigation-keeps-active-edge ()
  (ri-extend-test--with-buffer "foo\nbar\n\nspam\nbaz\n\nlol"
    (setq sr-submode 'paragraph)
    (should (ri--enter-extend))
    (ri-extend-nav-next)
    (let ((bounds (ri--selection-bounds)))
      (should (equal
               (buffer-substring-no-properties
                (car bounds) (cdr bounds))
               "foo\nbar\n\nspam\nbaz\n"))
      (should (eq (ri--selection-state-active-edge ri--selection)
                  'end))
      (should (= (point) (1- (cdr bounds)))))
    (ri-extend-nav-prev)
    (let ((bounds (ri--selection-bounds)))
      (should (equal
               (buffer-substring-no-properties
                (car bounds) (cdr bounds))
               "foo\nbar\n"))
      (should (= (point) (1- (cdr bounds)))))
    (ri--exit-extend)

    (search-forward "spam")
    (goto-char (match-beginning 0))
    (should (ri--enter-extend))
    (ri-swap-cursor)
    (ri-extend-nav-prev)
    (let ((bounds (ri--selection-bounds)))
      (should (equal
               (buffer-substring-no-properties
                (car bounds) (cdr bounds))
               "foo\nbar\n\nspam\nbaz\n"))
      (should (eq (ri--selection-state-active-edge ri--selection)
                  'start))
      (should (= (point) (car bounds))))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-line-down-does-not-highlight-newline ()
  (ri-extend-test--with-buffer "foo\nbar\n"
    (setq sr-submode 'line)
    (should (ri--enter-extend))
    (ri-extend-nav-down)
    (should (= (point) 7))
    (let ((bounds (ri--selection-bounds)))
      (should (equal bounds (cons 1 8)))
      (should (equal (buffer-substring-no-properties
                      (car bounds) (cdr bounds))
                     "foo\nbar"))
      (dolist (pos '(1 2 3 5 6 7))
        (should (ri-extend-test--highlighted-p pos)))
      (dolist (pos '(4 8))
        (should-not (ri-extend-test--highlighted-p pos))))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-parent-line-matches-ki-and-extend-edges ()
  (ri-extend-test--with-buffer "outer\n  inner\n    leaf\n"
    (let* ((outer (point-min))
           (outer-line (line-beginning-position))
           (inner
            (save-excursion
              (forward-line 1)
              (back-to-indentation)
              (point)))
           (inner-line
            (save-excursion
              (forward-line 1)
              (line-beginning-position)))
           (leaf
            (save-excursion
              (forward-line 2)
              (back-to-indentation)
              (point)))
           (leaf-line
            (save-excursion
              (forward-line 2)
              (line-beginning-position)))
           (leaf-end
            (save-excursion
              (forward-line 2)
              (line-end-position))))
      (cl-letf
          (((symbol-function 'sr--require-node-parser)
            (lambda (&optional _feature) 'fake))
           ((symbol-function 'sr--parent-line-position)
            (lambda ()
              (cond
               ((= (line-beginning-position) leaf-line) inner)
               ((= (line-beginning-position) inner-line) outer)
               ((= (line-beginning-position) outer-line) nil)))))
        (setq sr-submode 'line)
        (goto-char leaf)
        (ri-parent-line)
        (should (= (point) inner))
        (ri-parent-line)
        (should (= (point) outer))

        (goto-char leaf)
        (should (ri--enter-extend))
        (let ((before (ri--selection-bounds)))
          ;; Parent Line cannot move an end edge backward without putting
          ;; point inside the selection; an explicit cursor swap is required.
          (ri-parent-line)
          (should (equal (ri--selection-bounds) before))
          (should (= (point) (1- (cdr before)))))

        (ri-swap-cursor)
        (should
         (eq (ri--selection-state-active-edge ri--selection) 'start))
        (ri-parent-line)
        (should (equal (ri--selection-bounds) (cons inner leaf-end)))
        (should (= (point) inner))
        (ri-parent-line)
        (should (equal (ri--selection-bounds) (cons outer leaf-end)))
        (should (= (point) outer))
        (should
         (eq (ri--selection-state-active-edge ri--selection) 'start))
        (ri--exit-extend)))))


(ert-deftest ri-extend-test-line-to-word-keeps-newlines-unpainted ()
  (ri-extend-test--with-buffer "foo\nbar\nbaz\n"
    (setq sr-submode 'line)
    (should (ri--enter-extend))
    (ri-extend-nav-down)
    (ri-extend-nav-down)
    (let ((line-bounds (ri--selection-bounds)))
      (should (equal line-bounds (cons 1 12)))
      (ri-extend-set-word-mode)
      (should (eq sr-submode 'word))
      (should (equal (ri--selection-bounds) line-bounds))
      (dolist (pos '(1 2 3 5 6 7 9 10 11))
        (should (ri-extend-test--highlighted-p pos)))
      (dolist (pos '(4 8 12))
        (should-not (ri-extend-test--highlighted-p pos))))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-swaps-normal-unit-cursor ()
  (ri-extend-test--with-buffer "foo bar"
    (setq sr-submode 'word)
    (ri-swap-cursor)
    (should (= (point) 3))
    (ri-swap-cursor)
    (should (= (point) 1))))

(ert-deftest ri-extend-test-node-error-survives-key-release ()
  (ri-extend-test--with-buffer "plain text"
    (let ((sr-node-language-alist
           '((fundamental-mode . deliberately-missing)))
          (kkp-chord-after-release-hook
           '(ri--restore-message-after-release))
          (ri--restore-message-after-release nil)
          restored)
      (should-error (ri-set-node-mode) :type 'user-error)
      (let ((expected ri--restore-message-after-release))
        (should (string-match-p
                 "NODE requires.*deliberately-missing"
                 expected))
        (cl-letf (((symbol-function 'kkp-chord--parse)
                   (lambda (_input)
                     (list :keycode ?d
                           :event-type kkp-chord--event-release
                           :modifier-num 0)))
                  ((symbol-function 'kkp-chord--on-release) #'ignore)
                  ((symbol-function 'message)
                   (lambda (format-string &rest args)
                     (setq restored (apply #'format format-string args)))))
          (should (equal
                   (kkp-chord--translate-advice #'ignore "release")
                   [])))
        (should (equal restored expected))
        (should-not ri--restore-message-after-release)))))

(ert-deftest ri-extend-test-registers-normal-navigation-bindings ()
  (let ((mini-modal-map (make-sparse-keymap))
        (minor-mode-alist nil)
        (find-file-hook nil)
        (kkp-chord-after-release-hook nil)
        (sr-highlight-predicate nil)
        (status-frame-height 0)
        ri-tabs-enabled)
    (cl-letf (((symbol-function 'modal-cursor-mode) #'ignore)
              ((symbol-function 'ri-tabs-mode)
               (lambda (&optional arg)
                 (setq ri-tabs-enabled arg)))
              ((symbol-function 'mini-modal-setup) #'ignore)
              ((symbol-function 'kkp-chord-mode) #'ignore)
              ((symbol-function 'global-kkp-mode) #'ignore)
              ((symbol-function 'buffer-list)
               (lambda (&optional _frame) nil)))
      (ri-enable)
      (should (equal ri-tabs-enabled 1))
      (should (eq (lookup-key mini-modal-map "/")
                  #'ri-swap-cursor))
      (should (keymapp (lookup-key mini-modal-map (kbd "C-h"))))
      (should (eq (lookup-key mini-modal-map (kbd "C-h v"))
                  #'describe-variable))
      (should (eq (lookup-key ri--normal-help-map (kbd "C-h"))
                  'help-command))
      (should (eq (lookup-key ri--normal-help-map "/")
                  #'ri-swap-cursor))
      (should (eq (lookup-key mini-modal-map "f")
                  #'ri-toggle-extend))
      (should (commandp (lookup-key mini-modal-map "f")))
      (should (eq (lookup-key mini-modal-map "d")
                  #'ri-set-node-mode))
      (should (eq (lookup-key ri--normal-help-map "d")
                  #'ri-set-node-mode))
      (should (eq (lookup-key mini-modal-map "E")
                  #'ri-extend-set-paragraph-mode))
      (should (eq (lookup-key ri--normal-help-map "E")
                  #'ri-extend-set-paragraph-mode))
      (should (eq (lookup-key mini-modal-map "I")
                  #'ri-join-lines))
      (should (eq (lookup-key ri--normal-help-map "I")
                  #'ri-join-lines))
      (should (eq (lookup-key mini-modal-map "J")
                  #'ri-dedent))
      (should (eq (lookup-key ri--normal-help-map "J")
                  #'ri-dedent))
      (should (eq (lookup-key mini-modal-map "L")
                  #'ri-indent))
      (should (eq (lookup-key ri--normal-help-map "L")
                  #'ri-indent))
      (should (eq (lookup-key mini-modal-map "x")
                  #'ri--press-layer))
      (should (eq (lookup-key ri--normal-help-map "x")
                  #'ri-cut-selection))
      (should (eq (lookup-key mini-modal-map ".")
                  #'ri-parent-line))
      (should (eq (lookup-key ri--normal-help-map ".")
                  #'ri-parent-line))
      (dolist (case '((paragraph "PARAGRAPH")
                      (node "NODE")))
        (let ((sr-submode (car case)))
          (should (equal (ri--submode-name) (cadr case))))))))

(ert-deftest ri-extend-test-ri-enable-shows-tabs-for-new-file ()
  (let ((buffer (generate-new-buffer "ri-tabs-after-enable"))
        (mini-modal-map (make-sparse-keymap))
        (minor-mode-alist nil)
        (find-file-hook nil)
        (after-set-visited-file-name-hook nil)
        (kill-buffer-hook nil)
        (first-change-hook nil)
        (after-save-hook nil)
        (after-revert-hook nil)
        (window-selection-change-functions nil)
        (window-buffer-change-functions nil)
        (window-size-change-functions nil)
        (after-make-frame-functions nil)
        (kkp-chord-after-release-hook nil)
        (sr-highlight-predicate nil)
        (status-frame-height 0)
        (ri-tabs-mode nil))
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'modal-cursor-mode) #'ignore)
                    ((symbol-function 'mini-modal-setup) #'ignore)
                    ((symbol-function 'kkp-chord-mode) #'ignore)
                    ((symbol-function 'ri-chord-setup) #'ignore)
                    ((symbol-function 'global-kkp-mode) #'ignore)
                    ((symbol-function 'ri--maybe-enable-semantic-regions)
                     #'ignore)
                    ((symbol-function 'buffer-list)
                     (lambda (&optional _frame) (list buffer))))
            (set-window-buffer (selected-window) buffer)
            (ri-enable)
            (with-current-buffer buffer
              (setq buffer-file-name "/tmp/ri-tabs-after-enable.el")
              (run-hooks 'find-file-hook)
              (should ri-tabs-mode)
              (should-not tab-line-mode)
              (ri-tabs--refresh)
              (let* ((surface
                      (gethash (selected-frame)
                               ri-tabs--surface-windows))
                     (items (ri-tabs--visible-items (selected-frame))))
                (should (window-live-p surface))
                (should (window-parameter surface 'ri-tabs-surface))
                (should (= (length items) 1))
                (should (eq (ri-tabs--item-state (car items)) 'active))
                (should
                 (equal
                  (substring-no-properties
                   (ri-tabs--item-display (car items)))
                  " [ ] ri-tabs-after-enable.el "))))))
      (when ri-tabs-mode
        (ri-tabs-mode -1))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))))

(ert-deftest ri-extend-test-registers-cut-chord ()
  (let ((kkp-chord--mod-maps (make-hash-table :test 'eql))
        (kkp-chord--tap-actions (make-hash-table :test 'eql))
        (kkp-chord--predicates (make-hash-table :test 'eql))
        (kkp-chord--press-actions (make-hash-table :test 'eql))
        (kkp-chord--release-actions (make-hash-table :test 'eql)))
    (ri-chord-setup)
    (should (eq (gethash ?x kkp-chord--mod-maps)
                ri--cut-layer-map))
    (should (eq (gethash ?x kkp-chord--tap-actions)
                #'ri-cut-selection))
    (dolist (binding '(("j" . ri-cut-left)
                       ("l" . ri-cut-right)
                       ("u" . ri-cut-prev)
                       ("o" . ri-cut-next)
                       ("y" . ri-cut-first)
                       ("p" . ri-cut-last)))
      (should (eq (lookup-key ri--cut-layer-map (car binding))
                  (cdr binding))))))

(ert-deftest ri-extend-test-cut-selection ()
  (ri-extend-test--with-buffer "foo bar"
    (let ((kill-ring nil))
      (setq sr-submode 'word)
      (should (ri--enter-extend))
      (ri-extend-nav-right)
      (should (equal (ri--selection-bounds) (cons 1 8)))
      (ri-cut-selection)
      (should (equal (buffer-string) ""))
      (should (equal kill-ring '("foo bar")))
      (should-not (ri--selection-active-p)))))

(ert-deftest ri-extend-test-join-lines-matches-ki ()
  (ri-extend-test--with-buffer "foo\n    spam bar"
    (setq sr-submode 'word)
    (goto-char (point-max))
    (backward-char)
    (should (equal (ri--selection-bounds) (cons 14 17)))
    (ri-join-lines)
    (should (equal (buffer-string) "foospam bar"))
    (should (= (point) 11))
    (should (equal (ri--selection-bounds) (cons 9 12)))
    ;; The first line has no previous line, so joining it is a no-op.
    (ri-join-lines)
    (should (equal (buffer-string) "foospam bar"))))

(ert-deftest ri-extend-test-join-lines-preserves-extend-selection ()
  (ri-extend-test--with-buffer "foo\n    spam bar"
    (setq sr-submode 'word)
    (goto-char (point-max))
    (backward-char)
    (should (ri--enter-extend))
    (should (equal (ri--selection-bounds) (cons 14 17)))
    (ri-join-lines)
    (should (equal (buffer-string) "foospam bar"))
    (should (ri--selection-active-p))
    (should (equal (ri--selection-bounds) (cons 9 12)))
    (should (= (point) 11))
    (should (eq (ri--selection-state-active-edge ri--selection) 'end))
    (ri-join-lines)
    (should (equal (ri--selection-bounds) (cons 9 12)))
    (ri--exit-extend)))

(ert-deftest ri-extend-test-indent-dedent-single-line-matches-ki ()
  (ri-extend-test--with-buffer "fom"
    (setq sr-submode 'char)
    (ri-indent)
    (should (equal (buffer-string) "    fom"))
    (should (= (point) 5))
    (should (equal (ri--selection-bounds) (cons 5 6)))
    (ri-dedent)
    (should (equal (buffer-string) "fom"))
    (should (= (point) 1))
    (should (equal (ri--selection-bounds) (cons 1 2)))))

(ert-deftest ri-extend-test-indent-dedent-preserves-extend-edges ()
  (dolist (swap '(nil t))
    (ri-extend-test--with-buffer
        "fn main() {\n    foo()\n}\nafter\n"
      (setq sr-submode 'line-star)
      (should (ri--enter-extend))
      (ri-extend-nav-down)
      (ri-extend-nav-down)
      (when swap
        (ri-swap-cursor))
      (let ((active-edge
             (ri--selection-state-active-edge ri--selection)))
        (ri-indent)
        (should
         (equal (buffer-string)
                "    fn main() {\n        foo()\n    }\nafter\n"))
        (should (ri--selection-active-p))
        (should (eq (ri--selection-state-active-edge ri--selection)
                    active-edge))
        (should (equal (ri--selection-bounds) (cons 5 36)))
        (should
         (equal (buffer-substring-no-properties 5 36)
                "fn main() {\n        foo()\n    }"))
        (should (= (point) (if (eq active-edge 'end) 35 5)))
        (ri-dedent)
        (should
         (equal (buffer-string)
                "fn main() {\n    foo()\n}\nafter\n"))
        (should (equal (ri--selection-bounds) (cons 1 24)))
        (should (= (point) (if (eq active-edge 'end) 23 1)))))))

(ert-deftest ri-extend-test-dedent-removes-only-available-indentation ()
  (ri-extend-test--with-buffer
      "fn main() {\n    foo()\n}\nafter\n"
    (setq sr-submode 'line-star)
    (should (ri--enter-extend))
    (ri-extend-nav-down)
    (ri-extend-nav-down)
    (ri-dedent)
    (should
     (equal (buffer-string)
            "fn main() {\nfoo()\n}\nafter\n"))
    (should
     (equal
      (buffer-substring-no-properties
       (car (ri--selection-bounds))
       (cdr (ri--selection-bounds)))
      "fn main() {\nfoo()\n}"))
    (should (= (point) (1- (cdr (ri--selection-bounds)))))))

(ert-deftest ri-extend-test-mode-line-remaps-eglot-label ()
  (with-temp-buffer
    (ri--mode-line-enable)
    (let ((eglot-remap (assq 'eglot-mode-line face-remapping-alist)))
      (should eglot-remap)
      (should (memq 'ri-mode-line eglot-remap)))
    (should (equal (face-attribute 'ri-mode-line :foreground nil t)
                   "#ffffff"))
    (should (equal (face-attribute 'ri-mode-line :background nil t)
                   "#3478c6"))))

(provide 'ri-extend-test)
;;; ri-extend-test.el ends here

(ert-deftest ri-extend-test-node-down-enters-elisp-string-content ()
  (ri-extend-test--with-buffer "\"melpa\""
    (unless (and (treesit-available-p)
                 (treesit-language-available-p 'elisp))
      (ert-skip "Elisp tree-sitter grammar unavailable"))
    (emacs-lisp-mode)
    (treesit-parser-create 'elisp)
    (setq sr-submode 'node
          sr--node-current nil)
    (sr--node-clear-virtual)
    (goto-char (point-min))
    (sr--update-highlight)
    (ri-extend-nav-down)
    (should (equal (sr--get-current-unit-bounds) (cons 2 7)))
    (should (equal (buffer-substring-no-properties
                    (car (sr--get-current-unit-bounds))
                    (cdr (sr--get-current-unit-bounds)))
                   "melpa"))
    (dolist (pos '(2 3 4 5 6))
      (should (ri-extend-test--highlighted-p pos)))
    (should-not (ri-extend-test--highlighted-p 1))
    (should-not (ri-extend-test--highlighted-p 7))
    (ri-extend-nav-up)
    (should (equal (sr--get-current-unit-bounds) (cons 1 8)))))

;;; Mouse retargeting ---------------------------------------------------------

(ert-deftest ri-mouse-test-norm-binds-only-primary-click ()
  (let ((old-mouse (lookup-key mini-modal-map [mouse-1])))
    (unwind-protect
        (progn
          (ri-mouse-setup)
          (should (eq (lookup-key mini-modal-map [mouse-1])
                      #'ri-mouse-set-point))
          (should-not (lookup-key mini-modal-map [drag-mouse-1]))
          (should-not (lookup-key mini-modal-map [wheel-up])))
      (define-key mini-modal-map [mouse-1] old-mouse))))

(ert-deftest ri-mouse-test-click-moves-before-retarget ()
  (ri-extend-test--with-buffer "alpha beta\n"
    (setq mini-modal-mode t
          sr-mode t
          sr-submode 'word)
    (let (calls)
      (cl-letf (((symbol-function 'ri-mouse--target-window)
                 (lambda (_event) t))
                ((symbol-function 'ri-mouse--text-position)
                 (lambda (_event) 8))
                ((symbol-function 'mouse-set-point)
                 (lambda (_event)
                   (push 'mouse calls)
                   (goto-char 8)))
                ((symbol-function 'sr-retarget-at-position)
                 (lambda (pos)
                   (push (list 'retarget pos) calls))))
        (ri-mouse-set-point '(mouse-1 dummy))
        (should (= (point) 8))
        (should (equal (nreverse calls)
                       '(mouse (retarget 8))))))))

(ert-deftest ri-mouse-test-click-exits-extend-and-starts-fresh-unit ()
  (ri-extend-test--with-buffer "alpha beta\n"
    (setq mini-modal-mode t
          sr-mode t
          sr-submode 'word)
    (goto-char 2)
    (should (ri--enter-extend))
    (should (ri--selection-active-p))
    (cl-letf (((symbol-function 'ri-mouse--target-window)
               (lambda (_event) t))
              ((symbol-function 'ri-mouse--text-position)
               (lambda (_event) 8))
              ((symbol-function 'mouse-set-point)
               (lambda (_event) (goto-char 8))))
      (ri-mouse-set-point '(mouse-1 dummy)))
    (should-not (ri--selection-active-p))
    (should (= (point) 8))
    (should (equal (sr--get-current-unit-bounds) (cons 7 11)))))
