;;; ri-lsp-test.el --- Tests for Ri LSP navigation -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'ri)

(defun ri-lsp-test--raw-binding (map event)
  "Return MAP's raw binding for EVENT, including its menu label."
  (let (found)
    (map-keymap (lambda (candidate binding)
                  (when (equal candidate event)
                    (setq found binding)))
                map)
    found))

(defun ri-lsp-test--enter-word-extend ()
  "Enter Extend on the word at point in the current test buffer."
  (mini-modal-mode 1)
  (insert "alpha beta")
  (goto-char 2)
  (sr-set-word-mode)
  (should (ri--enter-extend)))

(ert-deftest ri-lsp-test-space-layer-preserves-ki-bindings-and-labels ()
  (dolist (spec '((?Z "Out Calls" ri-find-outgoing-calls)
                  (?z "In Calls" ri-find-incoming-calls)
                  (?x "Def" ri-find-definition)
                  (?X "Decl" ri-find-declaration)
                  (?c "Type" ri-find-type-definition)
                  (?V "Ref+" ri-find-references-with-declaration)
                  (?v "Ref-" ri-find-references-without-declaration)
                  (?b "Impl" ri-find-implementations)))
    (let ((binding (ri-lsp-test--raw-binding ri--space-layer-map
                                             (car spec))))
      (should (equal binding
                     (list 'menu-item (cadr spec) (caddr spec))))))
  (should (eq (lookup-key ri--space-layer-map "k") #'ri-pick-menu))
  (should (eq (lookup-key ri--space-layer-map (kbd "<escape>"))
              #'ri--exit-menu)))

(ert-deftest ri-lsp-test-pick-layer-preserves-ki-bindings-and-labels ()
  (dolist (spec '((?f "Buffer" ri-pick-buffer)
                  (?d "File" ri-pick-file)
                  (?s "Symbol (Document)" ri-pick-document-symbol)
                  (?S "Symbol (Workspace)" ri-pick-workspace-symbol)))
    (should
     (equal (ri-lsp-test--raw-binding ri--pick-layer-map (car spec))
            (list 'menu-item (cadr spec) (caddr spec)))))
  (should (eq (lookup-key ri--pick-layer-map (kbd "<escape>"))
              #'ri--exit-menu)))

(ert-deftest ri-lsp-test-pick-menu-opens-legend-and-transient-map ()
  (let (shown transient)
    (cl-letf (((symbol-function 'keymap-legend-show)
               (lambda (&rest arguments) (setq shown arguments)))
              ((symbol-function 'set-transient-map)
               (lambda (map keep &optional exit)
                 (setq transient (list map keep exit)))))
      (ri-pick-menu))
    (should (equal (list (car shown) (caddr shown))
                   '("Pick" (:title "Pick"))))
    (should (eq (cadr shown) ri--pick-layer-map))
    (should (eq (car transient) ri--pick-layer-map))
    (should (eq (cadr transient) t))
    (should (functionp (caddr transient)))))

(ert-deftest ri-lsp-test-picker-handoff-hides-legend-before-opening ()
  (let ((ri--menu-state 'pick)
        events
        close)
    (cl-letf (((symbol-function 'set-transient-map)
               (lambda (map &rest _)
                 (push (list 'transient map ri--menu-state) events)))
              ((symbol-function 'keymap-legend-hide)
               (lambda ()
                 (push (list 'legend-hidden ri--menu-state) events)))
              ((symbol-function 'ri--hide-frame)
               (lambda ()
                 (push (list 'frame-hidden ri--menu-state) events))))
      (ri--open-picker
       (lambda (on-close)
         (push (list 'opened ri--menu-state) events)
         (setq close on-close))))
    (should
     (equal (nreverse events)
            '((transient nil picker)
              (legend-hidden picker)
              (frame-hidden picker)
              (opened picker))))
    (should (eq ri--menu-state 'picker))
    (funcall close nil)
    (should-not ri--menu-state)))

(ert-deftest ri-lsp-test-picker-handoff-cleans-up-opener-error ()
  (let ((ri--menu-state 'pick)
        events
        caught)
    (cl-letf (((symbol-function 'set-transient-map)
               (lambda (map &rest _)
                 (push (list 'transient map ri--menu-state) events)))
              ((symbol-function 'keymap-legend-hide)
               (lambda ()
                 (push (list 'legend-hidden ri--menu-state) events)))
              ((symbol-function 'ri--hide-frame)
               (lambda ()
                 (push (list 'frame-hidden ri--menu-state) events))))
      (condition-case error
          (ri--open-picker
           (lambda (_on-close)
             (push (list 'opened ri--menu-state) events)
             (error "picker failed")))
        (error
         (setq caught error))))
    (should
     (equal (nreverse events)
            '((transient nil picker)
              (legend-hidden picker)
              (frame-hidden picker)
              (opened picker))))
    (should-not ri--menu-state)
    (should (eq (car caught) 'error))
    (should (equal (error-message-string caught) "picker failed"))))

(ert-deftest ri-lsp-test-space-opens-ki-layer-with-legend ()
  (let (shown transient)
    (cl-letf (((symbol-function 'keymap-legend-show)
               (lambda (title map spec)
                 (setq shown (list title map spec))))
              ((symbol-function 'set-transient-map)
               (lambda (map keep-pred &optional on-exit)
                 (setq transient (list map keep-pred on-exit)))))
      (ri-space-menu))
    (should (equal (list (nth 0 shown) (nth 2 shown))
                   '("Space" (:title "Space"))))
    (should (eq (nth 1 shown) ri--space-layer-map))
    (should (eq (nth 0 transient) ri--space-layer-map))
    (should (eq (nth 1 transient) t))
    (should (functionp (nth 2 transient))))
  (should-not (lookup-key ri--normal-help-map "n"))
  (should (eq (lookup-key ri--space-layer-map "x")
              #'ri-find-definition))
  (should (eq (lookup-key ri--space-layer-map "v")
              #'ri-find-references-without-declaration))
  (should (eq (plist-get (ri--layer-spec ?v) :tap)
              #'ri-paste-selection)))

(ert-deftest ri-lsp-test-dispatches-to-eglot-and-xref-entry-points ()
  (let (capabilities calls)
    (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
              ((symbol-function 'eglot-server-capable-or-lose)
               (lambda (capability) (push capability capabilities)))
              ((symbol-function 'xref-find-definitions)
               (lambda (&rest _)
                 (interactive)
                 (push '(xref definitions) calls)))
              ((symbol-function 'xref-find-references)
               (lambda (&rest _)
                 (interactive)
                 (push '(xref references) calls)))
              ((symbol-function 'eglot-find-declaration)
               (lambda () (push '(eglot declaration) calls)))
              ((symbol-function 'eglot-find-typeDefinition)
               (lambda () (push '(eglot type-definition) calls)))
              ((symbol-function 'eglot-find-implementation)
               (lambda () (push '(eglot implementation) calls)))
              ((symbol-function 'eglot-show-call-hierarchy)
               (lambda (direction) (push (list 'calls direction) calls)))
              ((symbol-function 'eglot--lsp-xref-helper)
               (lambda (&rest arguments)
                 (push (cons 'ref-minus arguments) calls))))
      (ri-lsp--find-outgoing-calls)
      (ri-lsp--find-incoming-calls)
      (ri-lsp--find-definition)
      (ri-lsp--find-declaration)
      (ri-lsp--find-type-definition)
      (ri-lsp--find-references-with-declaration)
      (ri-lsp--find-references-without-declaration)
      (ri-lsp--find-implementations))
    (should (member '(calls base) calls))
    (should (member '(calls incoming) calls))
    (should (member '(xref definitions) calls))
    (should (member '(eglot declaration) calls))
    (should (member '(eglot type-definition) calls))
    (should (member '(xref references) calls))
    (should (member '(eglot implementation) calls))
    (let ((ref-minus (assq 'ref-minus calls)))
      (should (equal (cdr ref-minus)
                     '(:textDocument/references
                       :extra-params
                       (:context (:includeDeclaration :json-false))))))
    (dolist (capability '(:callHierarchyProvider
                          :definitionProvider
                          :declarationProvider
                          :typeDefinitionProvider
                          :referencesProvider
                          :implementationProvider))
      (should (memq capability capabilities)))))

(ert-deftest ri-lsp-test-unmanaged-buffer-preserves-extend-exactly ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection))
          (submode sr-submode))
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () nil)))
        (should-error (ri-lsp--find-definition) :type 'user-error))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge))
      (should (eq sr-submode submode)))))

(ert-deftest ri-lsp-test-unsupported-capability-preserves-extend-exactly ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection))
          (submode sr-submode))
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
                ((symbol-function 'eglot-server-capable-or-lose)
                 (lambda (_) (user-error "Unsupported provider"))))
        (should-error (ri-lsp--find-definition) :type 'user-error))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge))
      (should (eq sr-submode submode)))))

(ert-deftest ri-lsp-test-supported-navigation-exits-extend-before-moving ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let (extend-active-during-dispatch)
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
                ((symbol-function 'eglot-server-capable-or-lose) #'ignore)
                ((symbol-function 'xref-find-definitions)
                 (lambda (&rest _)
                   (interactive)
                   (setq extend-active-during-dispatch
                         (ri--selection-active-p))
                   (goto-char (point-max)))))
        (ri-lsp--find-definition))
      (should-not extend-active-during-dispatch)
      (should-not (ri--selection-active-p))
      (should (= (point) (point-max))))))

(ert-deftest ri-lsp-test-opening-and-cancelling-space-preserves-extend ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection)))
      (cl-letf (((symbol-function 'keymap-legend-show) #'ignore)
                ((symbol-function 'keymap-legend-hide) #'ignore)
                ((symbol-function 'set-transient-map) #'ignore)
                ((symbol-function 'ri--hide-frame) #'ignore))
        (ri-space-menu)
        (ri--exit-menu))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge)))))

(ert-deftest ri-lsp-test-public-command-preserves-eglot-user-error ()
  (let ((ri--restore-message-after-release nil)
        (ri--restore-message-until-command-end nil)
        (ri--menu-state 'space))
    (cl-letf (((symbol-function 'set-transient-map) #'ignore)
              ((symbol-function 'keymap-legend-hide) #'ignore)
              ((symbol-function 'ri--hide-frame) #'ignore)
              ((symbol-function 'eglot-current-server) (lambda () nil)))
      (should-error (ri-find-definition) :type 'user-error))
    (should (string-match-p "Eglot" ri--restore-message-after-release))
    (should-not ri--menu-state)))

(ert-deftest ri-lsp-test-document-picker-preflight-preserves-extend ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection)))
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () nil)))
        (should-error (ri-lsp-pick-document-symbols) :type 'user-error))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge)))))

(ert-deftest ri-lsp-test-flattens-hierarchical-document-symbols ()
  (with-temp-buffer
    (insert "alpha")
    (let* ((name (propertize "child" 'imenu-kind "Function"))
           (entries (list (cons "Module" (list (cons name 2)))))
           (items (ri-lsp--flatten-imenu entries (current-buffer)))
           (item (car items))
           (target (ri-pick-item-target item)))
      (should (equal (ri-pick-item-label item) "Module › child"))
      (should (equal (ri-pick-item-annotation item) "Function"))
      (should (eq (plist-get target :buffer) (current-buffer)))
      (should (= (plist-get target :position) 2)))))

(ert-deftest ri-lsp-test-accepted-document-symbol-exits-extend-before-jump ()
  (save-window-excursion
    (with-temp-buffer
      (ri-lsp-test--enter-word-extend)
      (let ((item
             (ri-pick-item-create
              :label "beta"
              :target (list :buffer (current-buffer)
                            :position (copy-marker 8)))))
        (cl-letf (((symbol-function 'xref-push-marker-stack) #'ignore)
                  ((symbol-function 'ri-lsp--refresh-after-jump) #'ignore))
          (ri-lsp--accept-document-symbol item))
        (should-not (ri--selection-active-p))
        (should (= (point) 8))))))

(ert-deftest ri-lsp-test-workspace-provider-normalizes-and-cancels ()
  (with-temp-buffer
    (let* ((symbol
            '(:name "main"
              :kind 12
              :containerName "app"
              :location
              (:uri "file:///tmp/project/src/main.el"
               :range
               (:start (:line 4 :character 0)
                :end (:line 4 :character 4)))))
           success-function
           cancel-hints
           delivered)
      (cl-letf (((symbol-function 'eglot--async-request)
                 (lambda (_server _method _params &rest arguments)
                   (setq success-function
                         (plist-get arguments :success-fn))
                   41))
                ((symbol-function 'eglot--cancel-inflight-async-requests)
                 (lambda (hints) (setq cancel-hints hints))))
        (let ((cancel
               (ri-lsp--workspace-provider
                (current-buffer) 'server "/tmp/project/" "main"
                (lambda (items) (setq delivered items))
                (lambda (error) (ert-fail error)))))
          (funcall success-function (vector symbol))
          (should (= (length delivered) 1))
          (should (equal (ri-pick-item-label (car delivered)) "main"))
          (should (eq (ri-pick-item-target (car delivered)) symbol))
          (funcall cancel)
          (should (equal cancel-hints '(:workspace/symbol))))))))

(provide 'ri-lsp-test)
;;; ri-lsp-test.el ends here
