;;; ri-lsp-test.el --- Tests for Ri LSP navigation -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'ri)

(defun ri-lsp-test--raw-binding (map event)
  "Return MAP's raw binding for EVENT, including its menu label."
  (let (found)
    (map-keymap (lambda (candidate binding)
                  (when (equal candidate event)
                    (setq found binding)))
                map)
    found))

(defun ri-lsp-test--enter-word-extend ()
  "Enter Extend on the word at point in the current test buffer."
  (mini-modal-mode 1)
  (insert "alpha beta")
  (goto-char 2)
  (sr-set-word-mode)
  (should (ri--enter-extend)))

(ert-deftest ri-lsp-test-space-layer-preserves-ki-bindings-and-labels ()
  (dolist (spec '((?Z "Out Calls" ri-find-outgoing-calls)
                  (?z "In Calls" ri-find-incoming-calls)
                  (?x "Def" ri-find-definition)
                  (?X "Decl" ri-find-declaration)
                  (?c "Type" ri-find-type-definition)
                  (?V "Ref+" ri-find-references-with-declaration)
                  (?v "Ref-" ri-find-references-without-declaration)
                  (?b "Impl" ri-find-implementations)))
    (let ((binding (ri-lsp-test--raw-binding ri--space-layer-map
                                             (car spec))))
      (should (equal binding
                     (list 'menu-item (cadr spec) (caddr spec))))))
  (should (eq (lookup-key ri--space-layer-map (kbd "<escape>"))
              #'ri--exit-menu)))

(ert-deftest ri-lsp-test-space-opens-ki-layer-with-legend ()
  (let (shown transient)
    (cl-letf (((symbol-function 'keymap-legend-show)
               (lambda (title map spec)
                 (setq shown (list title map spec))))
              ((symbol-function 'set-transient-map)
               (lambda (map keep-pred &optional on-exit)
                 (setq transient (list map keep-pred on-exit)))))
      (ri-space-menu))
    (should (equal (list (nth 0 shown) (nth 2 shown))
                   '("Space" (:title "Space"))))
    (should (eq (nth 1 shown) ri--space-layer-map))
    (should (eq (nth 0 transient) ri--space-layer-map))
    (should (eq (nth 1 transient) t))
    (should (functionp (nth 2 transient))))
  (should-not (lookup-key ri--normal-help-map "n"))
  (should (eq (lookup-key ri--space-layer-map "x")
              #'ri-find-definition))
  (should (eq (lookup-key ri--space-layer-map "v")
              #'ri-find-references-without-declaration))
  (should (eq (plist-get (ri--layer-spec ?v) :tap)
              #'ri-paste-selection)))

(ert-deftest ri-lsp-test-dispatches-to-eglot-and-xref-entry-points ()
  (let (capabilities calls)
    (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
              ((symbol-function 'eglot-server-capable-or-lose)
               (lambda (capability) (push capability capabilities)))
              ((symbol-function 'xref-find-definitions)
               (lambda (&rest _)
                 (interactive)
                 (push '(xref definitions) calls)))
              ((symbol-function 'xref-find-references)
               (lambda (&rest _)
                 (interactive)
                 (push '(xref references) calls)))
              ((symbol-function 'eglot-find-declaration)
               (lambda () (push '(eglot declaration) calls)))
              ((symbol-function 'eglot-find-typeDefinition)
               (lambda () (push '(eglot type-definition) calls)))
              ((symbol-function 'eglot-find-implementation)
               (lambda () (push '(eglot implementation) calls)))
              ((symbol-function 'eglot-show-call-hierarchy)
               (lambda (direction) (push (list 'calls direction) calls)))
              ((symbol-function 'eglot--lsp-xref-helper)
               (lambda (&rest arguments)
                 (push (cons 'ref-minus arguments) calls))))
      (ri-lsp--find-outgoing-calls)
      (ri-lsp--find-incoming-calls)
      (ri-lsp--find-definition)
      (ri-lsp--find-declaration)
      (ri-lsp--find-type-definition)
      (ri-lsp--find-references-with-declaration)
      (ri-lsp--find-references-without-declaration)
      (ri-lsp--find-implementations))
    (should (member '(calls base) calls))
    (should (member '(calls incoming) calls))
    (should (member '(xref definitions) calls))
    (should (member '(eglot declaration) calls))
    (should (member '(eglot type-definition) calls))
    (should (member '(xref references) calls))
    (should (member '(eglot implementation) calls))
    (let ((ref-minus (assq 'ref-minus calls)))
      (should (equal (cdr ref-minus)
                     '(:textDocument/references
                       :extra-params
                       (:context (:includeDeclaration :json-false))))))
    (dolist (capability '(:callHierarchyProvider
                          :definitionProvider
                          :declarationProvider
                          :typeDefinitionProvider
                          :referencesProvider
                          :implementationProvider))
      (should (memq capability capabilities)))))

(ert-deftest ri-lsp-test-unmanaged-buffer-preserves-extend-exactly ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection))
          (submode sr-submode))
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () nil)))
        (should-error (ri-lsp--find-definition) :type 'user-error))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge))
      (should (eq sr-submode submode)))))

(ert-deftest ri-lsp-test-unsupported-capability-preserves-extend-exactly ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection))
          (submode sr-submode))
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
                ((symbol-function 'eglot-server-capable-or-lose)
                 (lambda (_) (user-error "Unsupported provider"))))
        (should-error (ri-lsp--find-definition) :type 'user-error))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge))
      (should (eq sr-submode submode)))))

(ert-deftest ri-lsp-test-supported-navigation-exits-extend-before-moving ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let (extend-active-during-dispatch)
      (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'server))
                ((symbol-function 'eglot-server-capable-or-lose) #'ignore)
                ((symbol-function 'xref-find-definitions)
                 (lambda (&rest _)
                   (interactive)
                   (setq extend-active-during-dispatch
                         (ri--selection-active-p))
                   (goto-char (point-max)))))
        (ri-lsp--find-definition))
      (should-not extend-active-during-dispatch)
      (should-not (ri--selection-active-p))
      (should (= (point) (point-max))))))

(ert-deftest ri-lsp-test-opening-and-cancelling-space-preserves-extend ()
  (with-temp-buffer
    (ri-lsp-test--enter-word-extend)
    (let ((bounds (ri--selection-bounds))
          (position (point))
          (edge (ri--selection-state-active-edge ri--selection)))
      (cl-letf (((symbol-function 'keymap-legend-show) #'ignore)
                ((symbol-function 'keymap-legend-hide) #'ignore)
                ((symbol-function 'set-transient-map) #'ignore)
                ((symbol-function 'ri--hide-frame) #'ignore))
        (ri-space-menu)
        (ri--exit-menu))
      (should (equal (ri--selection-bounds) bounds))
      (should (= (point) position))
      (should (eq (ri--selection-state-active-edge ri--selection) edge)))))

(ert-deftest ri-lsp-test-public-command-preserves-eglot-user-error ()
  (let ((ri--restore-message-after-release nil)
        (ri--restore-message-until-command-end nil)
        (ri--menu-state 'space))
    (cl-letf (((symbol-function 'set-transient-map) #'ignore)
              ((symbol-function 'keymap-legend-hide) #'ignore)
              ((symbol-function 'ri--hide-frame) #'ignore)
              ((symbol-function 'eglot-current-server) (lambda () nil)))
      (should-error (ri-find-definition) :type 'user-error))
    (should (string-match-p "Eglot" ri--restore-message-after-release))
    (should-not ri--menu-state)))

(provide 'ri-lsp-test)
;;; ri-lsp-test.el ends here
